name: flutter_app_gr
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  dio: ^2.1.0
  cookie_jar: ^1.0.0
  flutter_swiper: ^1.1.4
  flutter_screenutil: ^0.4.2
  flutter_easyrefresh: ^1.2.7
  fluttertoast: ^2.1.1
  qr_flutter: ^3.0.1
  barcode_scan: ^0.0.3
  cached_network_image: ^1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/loading.png
    - images/flutter.png
    - images/head.jpg
    - images/arrow_right.png
    - images/ic_error.png
    - images/ic_empty.png
    - images/bg_ydy1.png
    - images/bg_ydy2.png
    - images/bg_ydy3.png
    - images/bg_ydy4.png
    - images/rczc.png
    - images/rcgy.png
    - images/rclk.png
    - images/zmyz.png
    - images/zgz.png
    - images/xlrz.png
    - images/dafw.png
    - images/xxpx.png
    - images/gd.png
    - images/zjfw.png
    - images/kefubai.png
    - images/yuanjiaojuxing1.png
    - images/saoyisao.png
    - images/sousuo.png
    - images/xiaoxi.png
    - images/zdqy.png
    - images/jiantou.png
    - images/rencaizixun.png
    - images/bq.png
    - images/rczcs.png
    - images/gygy.png
    - images/qngy.png
    - images/rcgys.png
    - images/zmyzs.png
    - images/rclc.png
    - images/hd.png
    - images/ycgzz.png
    - images/xlrzs.png
    - images/tstd.png
    - images/zjfc.png
    - images/zjjt.png
    - images/zjjy.png
    - images/zjfp.png
    - images/ncsyrc.png
    - images/jnrcpx.png
    - images/zgzs.png
    - images/xczp.png
    - images/ks.png
    - images/xyzph.png
    - images/grxx.png
    - images/grhj.png
    - images/kjddh.png
    - images/datg.png
    - images/dazs.png
    - images/qtqk.png
    - images/dyhd.png
    - images/dyjn.png
    - images/dyzm.png
    - images/dzzgx.png
    - images/dzcy.png
    - images/cxzj.png
    - images/gyzj.png
    - images/zczx.png
    - images/jggs.png
    - images/tstd.png
    - images/xz.png
    - images/zx.png
    - images/kefu.png
    - images/b_xinfeng.png
    - images/search_news.png
    - images/caidan.png
    - images/icon_line.png
    - images/zxzd.png
    - images/wd_bg.png
    - images/admin.png
    - images/xiugai.png
    - images/setting.png
    - images/b_jianli.png
    - images/b_toudijilu.png
    - images/b_guanzhuhe.png
    - images/b_shoucang.png
    - images/b_bukejian.png
    - images/b_wdxz.png
    - images/b_bkgw.png
    - images/b_cjcx.png
    - images/b_kjzm.png
    - images/b_ly.png
    - images/icon_sy_x.png
    - images/icon_sy_n.png
    - images/icon_hd_x.png
    - images/icon_hd_n.png
    - images/icon_zx_x.png
    - images/icon_zx_n.png
    - images/icon_wd_x.png
    - images/icon_wd_n.png
    - images/icon_news_search.png
    - images/icon_jiantou_you.png
    - images/mr.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
